### PR TITLE
Removing cos()/sin() ambiguity

### PR DESCRIPTION
**Pull request by VeganPower**
Compiling Embree with OpenSubdiv I had an unresolved ambiguity in those two files.

### CODE REVIEW

**Comment by manuelk** [comment]
Hi

Thanks for the fix - can I ask which compiler was causing this ?

Also : i will need a signed CLA form before i can merge this pull-request (details here : http://graphics.pixar.com/opensubdiv/docs/intro.html#contributing)

**Comment by VeganPower** [comment]
I was compiling Embree ( embree.github.io ) with Opensubdiv support under a
fresh installed Mint distribution.
Compiler was Gcc 4.8 (don't remember the exact version .2 maybe ).
But the problem was caused by the huge number of include in Embree, and
probably some of them was including a C headers.

I'll send to the CLA as soon my HR send me the "relevant formal stuff"
That was the replay of my CEO: "Won’t be a problem – Matt will send you the
relevant formal stuff (he’s in Berlin at the moment)."
So probably Monday.



2015-01-26 23:56 GMT+00:00 Manuel Kraemer <notifications@github.com>:

> Hi
>
> Thanks for the fix - can I ask which compiler was causing this ?
>
> Also : i will need a signed CLA form before i can merge this pull-request
> (details here :
> http://graphics.pixar.com/opensubdiv/docs/intro.html#contributing)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PixarAnimationStudios/OpenSubdiv/pull/386#issuecomment-71564214>
> .
>



-- 
Dove alcuni vedono cavilli, io scorgo dettagli

**Comment by manuelk** [comment]
No problem - thanks !

I have been building with recent gcc versions as well and haven't been getting any resolution issues - so you are probably right : this is probably caused by other headers.

For the CLA, we already have one on file from Intel, i would just need a copy with your name added to the Schedule A (the original was signed by the VP of SSG - feel free to email me directly if you need names).

**Comment by VeganPower** [comment]
Hello, sorry for the late answer but our HR was away and when he returned
was submerged by a lot works.

In any case I'm working at Stainless Games <http://www.stainlessgames.com/>
not Intel.

I'm using Embree to create a raytracer to validate the game (Carmageddon
Reincarnation) shaders in prevision to insert area lights.

You will find the CLA attached.

2015-01-30 19:02 GMT+00:00 Manuel Kraemer <notifications@github.com>:

> No problem - thanks !
>
> I have been building with recent gcc versions as well and haven't been
> getting any resolution issues - so you are probably right : this is
> probably caused by other headers.
>
> For the CLA, we already have one on file from Intel, i would just need a
> copy with your name added to the Schedule A (the original was signed by the
> VP of SSG - feel free to email me directly if you need names).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PixarAnimationStudios/OpenSubdiv/pull/386#issuecomment-72252112>
> .
>



-- 
Dove alcuni vedono cavilli, io scorgo dettagli

**Comment by manuelk** [comment]
No problem at all.

I am not seeing the document though - could you please email it to opensubdiv at pixar dot com ?

**Comment by manuelk** [comment]
- CLA received and filed
- commit cherry-picked into the dev branch

We are all set - thank you very much !

**Pull request closed without merging**
