### PR TITLE
Added  a runtime flag to disable the glewExperimental flag

### PR DESCRIPTION
**Pull request by ielillo**
This flag is used by glew to show capabilities that are hidden by the graphic driver but sometimes those capabilities are reported as available but there is no implementation for them. This causes shader compilation issues as a result. The idea is to provide a way to disable the the experimental features and see if they resolve the the aforementioned issues.

### CODE REVIEW

**Comment by jcowles** [comment]
Cool! Couple minor notes:

 * Could you rebase this into a single commit
 * Kill the whitespace edit in examples/glViewer/CMakeLists.txt
 * Convert tabs to spaces in examples/glViewer/glViewer.cpp (take a look at the diff, the text is no longer aligned)
 * Remove the extra whitespace around the new if-condition

Thanks again for all your work on this!

**Comment by ielillo** [comment]
What do you mean by rebasing it into a single commit?

**Comment by jcowles** [comment]
I mean, run git rebase and squash the commits into a single commit at HEAD 

"git rebase -i upstream/dev" then squash appropriately, might do the trick, if you have upstream set to Pixar/OpenSubdiv. But you should research rebase and understand how it works before running that command.

Does that make sense?

--
Jeremy

Sent from my phone

**Comment by ielillo** [comment]
Ok, I did it in a different way. Basically I created a branch pointed at upstream/dev and then did a git merge --squash from the branch with the changes and then did a commit. Is that okay?

**Comment by jcowles** [comment]
However you do it is fine, as long as the commit history and diffs are clean.

**Comment by ielillo** [comment]
I've created a squashed commit and created a new pull request. I hope is what you want.

**Comment by jcowles** [comment]
Thanks, closing this.

**Pull request closed without merging**
