### PR TITLE
Spells

### PR DESCRIPTION
**Pull request by significant-bit**
Comment corrections from a mix of thorough reading and an automated spell check tool.

Most recent commit (phase 4) affects glPtexViewer's commandline output. Otherwise no functional changes.

### CODE REVIEW

**Comment by jcowles** [comment]
Thanks Mike!

Would you mind rebase-ing your change to clean up the spurious merges? If you need help, we might be able to fix it up for you on our end when someone gets a chance.

This is awesome!

**Comment by significant-bit** [comment]
Merged a branch into itself? That's what I get for using GitHub for Windows client for a terminal's job... I'll attempt to fix tomorrow.

**Comment by significant-bit** [comment]
Please use #731 "Spells take 2" instead of this one.

**Comment by jcowles** [comment]
Closing in favor of the cleaner PR #731

**Pull request closed without merging**
