### PR TITLE
Spells take 2

### PR DESCRIPTION
**Pull request by significant-bit**
Comment corrections from a mix of thorough reading and an automated spell check tool.

Most recent commit (phase 4) affects glPtexViewer's commandline output. Otherwise no functional changes.

Exact same change-set as earlier pull request #729 "Spells", but submitted cleaner git-wise. Thanks, cherry-pick!

### CODE REVIEW

**Comment by significant-bit** [comment]
#729 "Spells" asks for clarification in a few places. Please take a moment to make sure these comments match what the code is doing. I don't want to introduce filthy lies!

**Comment by jcowles** [comment]
This looks great Mike, thanks! I think all your questionable changes are correct. I'm just checking with the team to be sure merging isn't going to be disruptive for anyone.

(FYI, CLA has already been signed.)

**Comment by barfowl** [comment]
No objections or disruptions here.  I was wondering if we want to exclude Hbr from these changes though -- the consensus has been to avoid touching Hbr for other minor changes in the past (e.g. warning suppression).

It's been interesting and amusing to see some of the typos.  I have to wonder what a vertex or edge has to do to be considered an indecent vertex or edge (okay, the typo is "indicent" but it still reads "indecent"). :)

**Comment by jcowles** [comment]
+1 -- we shouldn't modify Hbr

--
Jeremy

**Comment by significant-bit** [comment]
Hbr changes should be limited to that one commit, pretty easy to exclude. Anything I need to do?

**Comment by jcowles** [comment]
No, we can fix that when we merge.

For the sake of stability and keeping the stability releases minimal, we are going to hold this for the 3.1.0 release. So we'll cut 3.0.3 first (in the next couple weeks) and then pull this change in for the 3.1.0 dev push.

Thanks again!

**Comment by significant-bit** [comment]
Still on track for 3.1 ?

**Comment by davidgyu** [comment]
Hi Mike,

We had quite a bit of functional code change for 3.1.0 so we (reluctantly) postponed pulling this fix. With that internal refactoring complete, we plan to cherry-pick this (along with some additional corrections from thomthom's PR #784) before the next release.

Thanks!
-David

**Comment by davidgyu** [comment]
I've cherry-picked these changes (skipping over the hbr edits), resolved conflicts, merged the result with #784, and posted an updated PR.

Thanks again for fixing all of these!

Closing this in favor of PR #918

**Pull request closed without merging**
