### PR TITLE
Rename and, or and not to &&, || and ! etc. Ref #779

### PR DESCRIPTION
**Pull request by thomthom**
This isn't a complete refactor. Given how many files need to be touched this is probably better done incrementally. 

I added a temporary CMake option to prevent the MSVC compatibility macros from being added to the solution. This can be all removed once the refactor is complete.

I have more fixes related to this, for DX and OpenGL - but I was going to submit PR separately so it's easier to review and test. With so many changes all over the place it's easy to introduce typo regressions so please review carefully.

Tested using the following config:

```
cmake ^
  -G "Visual Studio 12 2013 Win64" ^
  -D NO_EXAMPLES=1 ^
  -D NO_TUTORIALS=1 ^
  -D NO_REGRESSION=1 ^
  -D NO_MAYA=1 ^
  -D NO_PTEX=1 ^
  -D NO_DOC=1 ^
  -D NO_OMP=1 ^
  -D NO_TBB=1 ^
  -D NO_CUDA=1 ^
  -D NO_OPENCL=1 ^
  -D NO_OPENGL=1 ^
  -D NO_DX=1 ^
  -D NO_CLEW=1 ^
  -D NO_ISO646=1 ^
  ..
```

### CODE REVIEW

**Comment by thomthom** [comment]
Hmm... the message should have linked to #779 - doesn't seem to have happened.

**Comment by davidgyu** [comment]
Thanks Thomas! This looks like a good start. We'll pull this into dev now that 3.0.5 has been released. -David

**Comment by davidgyu** [comment]
We are finally ready to merge this fix. Thank you again and sorry for the delay!

There is a minor merge conflict with this request. If you resolve it in your branch I will merge. I see that you have follow on edits, so those branches will need to be resolved as well. Otherwise I am happy to cherry-pick the change.

Thanks!
-David

**Comment by thomthom** [comment]
I pulled the dev branch into this one and resolved the conflicts.

I do have a couple of other commits in the `dev-iso646-fix` branch, but I figured it'd be easier to do a PR for each one as they carry a lot of small changes all over the place.

**Comment by davidgyu** [comment]
Sounds great! I'll merge this and clear the way for your follow-up PRs. Thanks! -David

**Pull request merged**
