### PR TITLE
Fix win32 cmake generator without glew

### PR DESCRIPTION
**Pull request by hsdk**
- changed glew from a required to an optional dependency

### CODE REVIEW

**Comment by manuelk** [comment]
In this particular case, i believe GLEW is actually required - can i ask why you think this is not the case ?

**Comment by hsdk** [comment]
The required flag prevents generating the build files (see https://github.com/PixarAnimationStudios/OpenSubdiv/issues/358,  https://github.com/PixarAnimationStudios/OpenSubdiv/issues/373)  when OpenGL is found but GLEW is not available. With the change above, the build files are generated with and without GLEW. The rest of the cmake build script already treats GLEW as optional by checking for GLEW_FOUND before enabling the gl parts of the lib and the examples.

**Comment by manuelk** [comment]
GLEW is only optional with OS X - this may not be the case any longer, but originally, i believe that we needed it for Win & Linux, which is why the REQUIRED flag is selectively added outside of OS X.

There is a separate flag to disable OpenGL entirely, and then GLEW is not a requirement any more. Would that solve your problem ?

**Comment by manuelk** [comment]
Side note : please submit pull requests against the dev branch, not the master branch.

**Comment by hsdk** [comment]
Sorry for submitting the pull request against the master branch. The intention was to build OpenSubdiv out of the box on systems that have OpenGL but not GLEW. On these system, the flag to disable the OpenGL parts is currenly mandatory to build the lib instead of an option. 

The GL parts of the library require both OpenGL and GLEW and this is not changed by the patch.

**Comment by hsdk** [comment]
Sorry for submitting the pull request against the master branch. Shall i open a new request against the dev branch or just close this one?

**Comment by manuelk** [comment]
Not necessary - i can cherry-pick the change manually. Let's finish hashing this out first as i think i am still missing something...

Your change essentially makes GLEW optional any time GL is found, which AFAIK causes problems on Win & Linux where GLEW is mandatory.

**Comment by jcowles** [comment]
Closing -- Henry, please feel free to reopen if you're having this issue with the 3.0 dev branch!

**Pull request closed without merging**
