### PR TITLE
Fix typo: "buf" -> "bug"

### PR DESCRIPTION
**Pull request by nicholasbishop**

### CODE REVIEW

**Comment by jcowles** [comment]
Thanks!

To accept your request, we need a signed CLA (details here : http://graphics.pixar.com/opensubdiv/docs/intro.html#contributing), which is silly for this pull request, but if you plan to contribute in the future, it will be good to get it out of the way.

Let us know if you plan to sign it, otherwise I'll just go fix up the typo in a new change.

**Comment by nicholasbishop** [comment]
Sure, I'll send that along later today.

**Comment by manuelk** [comment]
Thanks for sending the CLA - i just filed it. We will merge your pull request as soon as we fix a recent mess in the commit history.

**Comment by manuelk** [comment]
Merged - thanks for submitting !

**Pull request closed without merging**
