### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ielillo**
I've been working on making the glViewer work on older machines. From the initial executions the program failed because the wrong opengl version hinting was being set in the function setGLCoreProfile. In order to fix that I decided to try different opengl versions and fail if none of the works. The version are 4.4, 4.2 and 3.2.

Another issue was the shader linking errors. The cause was that the wrong opengl version  was being set in the shader file. As a solution, I created a function to query for the current opengl version and use it to set the right shader version before compiling it.

Finally some parts of the code used the GLEW headers definitions to check if certain opengl capabilities were present, the issue with that is sometimes a driver says that certain capability is present but it does not says that it is really implemented. So if GLEW was present I used it to dynamically query the opengl capabilities falling back to headers definitions otherwise. 

Regarding the platforms  this code has been developed primarily on Windows and Linux so it should work on both. However it has not been compiled nor tested on the Mac platform, so I cannot guarantee that it will compile there or work.
I'm open to any suggestion or criticism.

### CODE REVIEW

**Comment by jcowles** [comment]
Thanks for the pull request! 

Do we have a signed CLA document from you? If not, could you email me one to me (jcowles at pixar)?

If you have already sent one, could you send me your name so I can verify?

**Comment by ielillo** [comment]
You are welcome. At this point I do not have a CLA, I have read it and
signed it. Should I sent first to opensubdiv-cla@pixar.com and then to you?
Best regards:
Ignacio

2015-05-05 14:48 GMT-03:00 Jeremy Cowles <notifications@github.com>:

**Comment by jcowles** [comment]
No, just the cla address is fine (I was concerned that it was out of date but it looks good).

--
Jeremy

**Comment by ielillo** [comment]
I have just sent the CLA.
Best regards:
Ignacio

2015-05-09 13:55 GMT-03:00 Jeremy Cowles <notifications@github.com>:

> No, just the cla address is fine (I was concerned that it was out of date
> but it looks good).
>
> --
> Jeremy
>
> Sent from my phone
>
>

**Comment by jcowles** [comment]
Received, thanks!

**Comment by ielillo** [comment]
I'm seeing the there is some merge conflicts for this pull request. Should I create a new pull request? if not, How can I fix it?

**Comment by takahito-tejima** [comment]
Hi Ignacio, thank you for the pull request!

I locally merged and tried your change. I had to change glewGetExtention to glewIsSupported since glewGetExtention("GL_ARB_tessellation_shader") returns false.

https://github.com/takahito-tejima/OpenSubdiv/tree/ielillo-dev

Could you confirm this fix works for your environment? And if it's ok, please make a new pull request. It would be great if you can rebase to the latest change on dev branch.

takahito

**Comment by ielillo** [comment]
Hi, I merged the changes from dev into my own branch but I had to make some modifications in the process to make it compile. I'll make another pull request explaining the changes.

**Comment by jcowles** [comment]
The new pull request fully replaces this one, correct?

Closing, but feel free to reopen if there is still something to merge here.

**Pull request closed without merging**
