### PR TITLE
Renamed per-patch face-varying access methods

### PR DESCRIPTION
**Pull request by davidgyu**
This matches more closely the pattern used elsewhere in Far:
    GetFVarPatchValues() --> GetPatchFVarValues()
    GetFVarPatchesValues() --> GetFVarValues()

### CODE REVIEW

**Comment by barfowl** [comment]
Is this all going to be hidden in 3.0 with the rest of the face-varying
patch work that's in progress, or is this functional to access the bilinear
face-varying values?

**Comment by davidgyu** [comment]
Right, this is part of the interface that is needed to access the bilinear face-varying values. I have a couple of follow up changes which will isolate and then remove the bicubic face-varying support from Far.

**Comment by barfowl** [comment]
Okay.  The trend in the existing topological face-varying queries is that
the channel argument come last, e.g.  GetFaceFVarValues(faceIndex,
channel).  The channel also usually defaults to 0 if unspecified in most
queries -- the expectation being that a lot of use cases only have one.

**Comment by davidgyu** [comment]
Good point. I'll fix that too. Thanks!

**Pull request merged**
