### PR TITLE
Fix find_package for zlib which requires all upper case ZLIB

### PR DESCRIPTION
**Pull request by nyue**

### CODE REVIEW

**Comment by davidgyu** [comment]
Good catch! I don't think we have an OpenSubdiv CLA from you (OpenSubdiv and USD have separate CLAs). Thanks! -David

**Comment by nyue** [comment]
Hi David,
I have now submitted the OpenSubdiv CLA (individual).
Cheers

**Comment by davidgyu** [comment]
Thanks Nicholas!

**Comment by davidgyu** [comment]
Oops, just realized this PR was to master instead of dev. I will fix that...

**Pull request merged**
