### PR TITLE
Fix typo in Far tutorial, GetFaceEdges() actually get face index, not edge index

### PR DESCRIPTION
**Pull request by Nazg-Gul**
Seems to be a typo unless i'm mistaken.

### CODE REVIEW

**Comment by jcowles** [comment]
Hi there, 

Yep, seems like a typo to me too. Have you already signed a CLA (http://graphics.pixar.com/opensubdiv/docs/contributing.html)?

Thanks for pointing that out and taking the time to make a pull request!

**Comment by Nazg-Gul** [comment]
Hey!

Yep, i've signed it already and have some patches merged back in OpenSubdiv 2.x days.

**Comment by jcowles** [comment]
Hmm, I'm not seeing anything on file for you (looking for Sergey Sharybin) -- what name/organization would it be associated with?

**Comment by Nazg-Gul** [comment]
it should be on my name indeed, but it's a bit weird you didn't find it. I've signed it and gave to Manuel when was visiting Pixar in 2013. And since then various patches were accepted already..

In any case, maybe it'll be easier to just sign it once again, just to be sure? :)

**Comment by jcowles** [comment]
Yeah, that would be easiest -- would you mind sending a new digital copy? 
Then I'll make sure it gets filed & logged correctly.

**Comment by Nazg-Gul** [comment]
Done, sent to the opensubdiv-cla mail.

**Comment by jcowles** [comment]
Excellent, thanks!

**Pull request merged**
