### PR TITLE
Moved primvar interpolation methods to new Far::PrimvarRefiner class

### PR DESCRIPTION
**Pull request by barfowl**
This change moves all generic primvar related methods (involving template parameters <T> et al) from Far::TopologyRefiner to the new public Far::PrimvarRefiner class.  Interfaces for the <T,U> classes remain unchanged.  All usage in tutorials and examples was updated.

### CODE REVIEW

**Comment by barfowl** [comment]
Now that this is clean I'll consolidate into a single commit, close this and resubmit.

**Comment by c64kernal** [comment]
Ha we collided.

**Comment by barfowl** [comment]
Nice catch on the protected/public: -- no, that's not intentional.  A local copy I tweak in my repository for some additional testing that should have been removed.  I'm reassembling the new commit and pull request now (probably an easier way if I wasn't such a git newbie...)

**Comment by c64kernal** [comment]
No worries!  For my part at least, I don't mind the list of commits you had at all.

**Pull request closed without merging**
